/* src/Application.svelte generated by Svelte v3.31.0 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	init,
	mount_component,
	safe_not_equal,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import Layout from "./routes/$layout.js";
import Index from "./routes/index.js";

function create_default_slot(ctx) {
	let index;
	let current;
	index = new Index({});

	return {
		c() {
			create_component(index.$$.fragment);
		},
		m(target, anchor) {
			mount_component(index, target, anchor);
			current = true;
		},
		i(local) {
			if (current) return;
			transition_in(index.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(index.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(index, detaching);
		}
	};
}

function create_fragment(ctx) {
	let layout;
	let current;

	layout = new Layout({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(layout.$$.fragment);
		},
		m(target, anchor) {
			mount_component(layout, target, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const layout_changes = {};

			if (dirty & /*$$scope*/ 1) {
				layout_changes.$$scope = { dirty, ctx };
			}

			layout.$set(layout_changes);
		},
		i(local) {
			if (current) return;
			transition_in(layout.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(layout.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(layout, detaching);
		}
	};
}

class Application extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Application;